spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/agilexperttask}
    username: ${SPRING_DATASOURCE_USERNAME:agile}
    password: ${SPRING_DATASOURCE_PASSWORD:agile}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  jackson:
    serialization:
      indent_output: true

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    org.hibernate.SQL: warn
    com.agilexperttask: info
